version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: npm
      - save_cache:
          key: "npm-packages"
          paths:  
            - /src/node_modules
      - run: npm run lint

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i      
      - run: npm run test

  analyze:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"  
      - run: npm audit

workflows:
  my_CI_PipelineWorkFlow:
    jobs:
      - build
      - test:
          requires:
           - build
      - analyze:
          requires:
           - test

#For the build job, npm run lint
#For the test job, npm run test
#For the analyze job, npm audit     
